#!/bin/bash
# Author : TheWatermelon
# bg_changer : ramdomly change wallpaper from a wallpapers directory, using feh

if [[ $# -ne 2 ]]; then
	echo "Usage : $0 <imgs directory> <sleep time>"
	exit
fi

wallpapers_dir=$1
wait_time=$2

wallpapers=();

for i in `ls $wallpapers_dir`; do
	wallpapers=(${wallpapers[@]} $wallpapers_dir$i);
done

while true; do
	rnd=$(( ( RANDOM % ${#wallpapers[@]} ) + 1 ))
	feh --bg-fill ${wallpapers[rnd]} &
	sleep $wait_time
done
