####################################
# Config file used by `sequestrum` #
####################################

options:
  base: &base
    dotfileDirectory: programmation/dotfiles

  editorsPackage:
    directoryName: editors
    links:
      - vimrc:            .vimrc
      - vim_plugins:      .vim/plugin_list.txt
      - vim_colorscheme:  .vim/colors/white.vim
      - emacs.el:         .emacs

  scriptsPackage:
    directoryName: scripts
    links:
      - batstatus:    bin/batstatus
      - tomato-timer: bin/tomato-timer
      - bg_changer:   bin/bg_changer
      - todo.sh:      bin/todo.sh


  termPackage:
    directoryName: term
    links:
      - tmuxrc:             .tmux.conf
      - conkyrc_tmux:       .conkyrc_tmux
      - zshrc:              .zshrc
      - shell_aliases:      .sh_aliases
      - shell_colors:       .sh_colors
      - shell_functions:    .sh_functions
      - spaceship-promptrc: .config/spaceship-prompt/spaceship-promptrc_classic

  xPackage:
    directoryName: x
    links:
      - dunstrc:                .config/dunst/dunstrc
      - i3_config:              .i3/config
      - polybar_config:         .config/polybar/config
      - rofirc:                 .config/rofi/config
      - rofi_theme.rasi:        .config/rofi/left_panel.rasi
      - termiterc:              .config/termite/config
      - qutebrowser_config:     .config/qutebrowser/config.py
      - libinput-gestures.conf: .config/libinput-gestures.conf
      - Xresources:             .Xresources
      - Xdefaults:              .Xdefaults
