####################################
# Config file used by `sequestrum` #
####################################

options:
  base: &base
    dotfileDirectory: programmation/dotfiles

  editorsPackage:
    directoryName: editors
    links:
      - vim_config:   .vimrc
      - vim_plugins:  .vim/plugin_list.txt
      - vim_theme:    .vim/colors/white.vim
      - emacs_config: .emacs

  scriptsPackage:
    directoryName: scripts
    links:
      - batstatus:    bin/batstatus
      - tomato-timer: bin/tomato-timer
      - bg_changer:   bin/bg_changer
      - todo.sh:      bin/todo.sh
      - polybarstart: bin/polybarstart


  termPackage:
    directoryName: term
    links:
      - tmux_config:              .tmux.conf
      - tmux_conky_config:        .conkyrc_tmux
      - zsh_config:               .zshrc
      - main-highlighter.zsh:     .oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/main/main-highlighter.zsh
      - shell_aliases:            .sh_aliases
      - shell_colors:             .sh_colors
      - shell_functions:          .sh_functions
      - spaceship-prompt_config:  .config/wal/templates/spaceship-promptrc

  xPackage:
    directoryName: x
    links:
      - dunst_config:             .config/wal/templates/dunst.config
      - i3_config:                .i3/config
      - polybar_config:           .config/wal/templates/polybar_config
      - rofi_config:              .config/rofi/config
      - rofi_theme:               .config/wal/templates/rofi_theme.rasi
      - termite_config:           .config/wal/templates/termite.config
      - qutebrowser_config:       .config/qutebrowser/config.py
      - libinput-gestures_config: .config/libinput-gestures.conf
      - splatmoji_config:         .config/splatmoji/splatmoji.config
      - Xresources:               .config/wal/templates/colors.Xresources
