#!/bin/bash
# Pomodoro timer
# Author : TheWatermelon

new_tomato()
(
	if [[ $# -eq 0 ]]; then
		# No argument : start pomodoro
		if [[ -f /tmp/tomato_timer ]]; then
			# Reading active status and pomodoro duration from file
			read active sec < /tmp/tomato_timer
			remaining=0
			for i in `seq $sec`; do
				if [[ $active -ne 0 ]]; then
					# Pomodoro in progress
					sleep 1 &
					remaining=$(( sec - i ))
					printf "%02d:%02d" $(( remaining/60 )) $(( remaining%60 ))
					echo 
					wait
				else
					# Pomodoro in pause
					while [[ $active -eq 0 ]]; do
						read active sec < /tmp/tomato_timer
						printf "(%02d:%02d)" $(( remaining/60 )) $(( remaining%60 ))
						echo 
						sleep 1
					done
				fi
				# Updating active status and pomodoro duration
				read active sec < /tmp/tomato_timer
			done
			# Pomodoro is over, destructing temporary file
			rm -f /tmp/tomato_timer
		else
			# No file : pomodoro icon
			echo 
		fi
	else
		# Getting pomodoro duration from argument
		sec=$1
		sec=$(( sec * 60 ))
		if [[ -f /tmp/tomato_timer ]]; then
			# Toggling pomodoro active status and updating duration
			read active old_sec < /tmp/tomato_timer
			echo "$(( (active + 1) % 2 )) $sec" > /tmp/tomato_timer
		else
			# Initializing pomodoro
			echo "1 $sec" > /tmp/tomato_timer
		fi
	fi
)

new_tomato $@
