
# Shell variables
# Generated by 'wal'
wallpaper="{wallpaper}"

# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'

# Colors
color0='#FFFFFF'
color1='#FF0000'
color2='#00FF00'
color3='#0000FF'
color4='#FFFF00'
color5='#00FFFF'
color6='#FF00FF'
color7='#FFFFFF'
color8='{color8}'
color9='{color9}'
color10='{color10}'
color11='{color11}'
color12='{color12}'
color13='{color13}'
color14='{color14}'
color15='{color15}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
